// Generated by scripts/render-room-stills.mjs from the local 3D room.
export const roomStills = {
  welcome: {
    src: "./assets/room-stills/welcome.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 0.492642,
        y: 0.338071,
        hidden: false,
      },
      notes: {
        x: 0.396441,
        y: 0.447699,
        hidden: false,
      },
      memories: {
        x: 0.801963,
        y: 0.312037,
        hidden: false,
      },
      trophy: {
        x: 0.776138,
        y: 0.497607,
        hidden: false,
      },
      skills: {
        x: 0.164882,
        y: 0.531802,
        hidden: false,
      },
      about: {
        x: 0.185183,
        y: 0.343548,
        hidden: false,
      },
      services: {
        x: 0.608564,
        y: 0.5296,
        hidden: false,
      },
    },
  },
  room: {
    src: "./assets/room-stills/room.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 0.473472,
        y: 0.324406,
        hidden: false,
      },
      notes: {
        x: 0.360789,
        y: 0.453581,
        hidden: false,
      },
      memories: {
        x: 0.828716,
        y: 0.272166,
        hidden: false,
      },
      trophy: {
        x: 0.805806,
        y: 0.481913,
        hidden: false,
      },
      skills: {
        x: 0.123843,
        y: 0.568535,
        hidden: false,
      },
      about: {
        x: 0.132274,
        y: 0.355145,
        hidden: false,
      },
      services: {
        x: 0.624614,
        y: 0.531631,
        hidden: false,
      },
    },
  },
  work: {
    src: "./assets/room-stills/work.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 0.5,
        y: 0.153248,
        hidden: false,
      },
      notes: {
        x: 0.01356,
        y: 0.895459,
        hidden: false,
      },
      memories: {
        x: 1.918726,
        y: -0.210506,
        hidden: true,
      },
      trophy: {
        x: 1.939053,
        y: 0.772256,
        hidden: true,
      },
      skills: {
        x: -0.452318,
        y: 1.046694,
        hidden: true,
      },
      about: {
        x: -0.665269,
        y: 0.191653,
        hidden: true,
      },
      services: {
        x: 1.402075,
        y: 0.880254,
        hidden: true,
      },
    },
  },
  writing: {
    src: "./assets/room-stills/writing.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 1.629619,
        y: -0.33989,
        hidden: true,
      },
      notes: {
        x: 0.774873,
        y: 0.20232,
        hidden: false,
      },
      memories: {
        x: 4.246128,
        y: -0.945332,
        hidden: true,
      },
      trophy: {
        x: 4.153501,
        y: 0.09121,
        hidden: true,
      },
      skills: {
        x: -0.643286,
        y: 1.863706,
        hidden: true,
      },
      about: {
        x: -0.749072,
        y: 0.561704,
        hidden: true,
      },
      services: {
        x: 2.946016,
        y: 0.858345,
        hidden: true,
      },
    },
  },
  about: {
    src: "./assets/room-stills/about.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: -0.53897,
        y: 0.465723,
        hidden: true,
      },
      notes: {
        x: -0.895215,
        y: 1.007739,
        hidden: true,
      },
      memories: {
        x: 0.5,
        y: 0.207074,
        hidden: false,
      },
      trophy: {
        x: 0.514912,
        y: 0.924761,
        hidden: false,
      },
      skills: {
        x: -1.236304,
        y: 1.104868,
        hidden: true,
      },
      about: {
        x: -1.3923,
        y: 0.482815,
        hidden: true,
      },
      services: {
        x: 0.121694,
        y: 0.996597,
        hidden: true,
      },
    },
  },
  achievements: {
    src: "./assets/room-stills/achievements.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: -0.560273,
        y: -0.245517,
        hidden: true,
      },
      notes: {
        x: -0.912842,
        y: 0.248187,
        hidden: true,
      },
      memories: {
        x: 0.532427,
        y: -0.478144,
        hidden: true,
      },
      trophy: {
        x: 0.48028,
        y: 0.200926,
        hidden: false,
      },
      skills: {
        x: -1.56293,
        y: 0.402874,
        hidden: true,
      },
      about: {
        x: -1.577412,
        y: -0.207482,
        hidden: true,
      },
      services: {
        x: -0.046456,
        y: 0.290923,
        hidden: true,
      },
    },
  },
  skills: {
    src: "./assets/room-stills/skills.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 2.075107,
        y: -0.609434,
        hidden: true,
      },
      notes: {
        x: 1.851104,
        y: 0.062312,
        hidden: true,
      },
      memories: {
        x: 2.96248,
        y: -0.749224,
        hidden: true,
      },
      trophy: {
        x: 2.728838,
        y: 0.234398,
        hidden: true,
      },
      skills: {
        x: 0.501431,
        y: 0.104974,
        hidden: false,
      },
      about: {
        x: 0.911528,
        y: -0.770991,
        hidden: true,
      },
      services: {
        x: 1.981846,
        y: 0.24377,
        hidden: true,
      },
    },
  },
  experience: {
    src: "./assets/room-stills/experience.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 1.449019,
        y: 0.241366,
        hidden: true,
      },
      notes: {
        x: 1.255103,
        y: 0.801934,
        hidden: true,
      },
      memories: {
        x: 2.195439,
        y: 0.034722,
        hidden: true,
      },
      trophy: {
        x: 2.015767,
        y: 0.803906,
        hidden: true,
      },
      skills: {
        x: 0.192215,
        y: 0.8627,
        hidden: false,
      },
      about: {
        x: 0.5,
        y: 0.192415,
        hidden: false,
      },
      services: {
        x: 1.415552,
        y: 0.846196,
        hidden: true,
      },
    },
  },
  services: {
    src: "./assets/room-stills/services.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: -0.780659,
        y: -0.715322,
        hidden: true,
      },
      notes: {
        x: -1.611401,
        y: -0.022876,
        hidden: true,
      },
      memories: {
        x: 1.684131,
        y: -1.82313,
        hidden: true,
      },
      trophy: {
        x: 1.675347,
        y: -0.797974,
        hidden: true,
      },
      skills: {
        x: -2.610259,
        y: 1.890303,
        hidden: true,
      },
      about: {
        x: -2.882949,
        y: 0.641362,
        hidden: true,
      },
      services: {
        x: 0.668823,
        y: 0.194082,
        hidden: false,
      },
    },
  },
  contact: {
    src: "./assets/room-stills/contact.jpg",
    width: 2048,
    height: 2048,
    anchors: {
      work: {
        x: 0.497305,
        y: 0.337967,
        hidden: false,
      },
      notes: {
        x: 0.4025,
        y: 0.445725,
        hidden: false,
      },
      memories: {
        x: 0.803921,
        y: 0.317933,
        hidden: false,
      },
      trophy: {
        x: 0.776606,
        y: 0.502979,
        hidden: false,
      },
      skills: {
        x: 0.165595,
        y: 0.525293,
        hidden: false,
      },
      about: {
        x: 0.189502,
        y: 0.337465,
        hidden: false,
      },
      services: {
        x: 0.607632,
        y: 0.531699,
        hidden: false,
      },
    },
  },
};
